language: node_js 
node_js: stable 
install:
    - npm install 
script:
    - hexo clean 
    - hexo g 
after_script:
    - cd ./public
    - git init
    - git config user.name "Yohole Huang" 
    - git config user.email "490767385@qq.com" 
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN_GITHUB}@${GH_REF_GITHUB}" master:master
    - git push --force --quiet "https://${GH_TOKEN_GITEE}@${GH_REF_GITEE}" master:master 
branches:
    only:
        - hexo 
env:
    global:
        - GH_REF_GITHUB: github.com/yohole/yohole.github.io.git
        - GH_REF_GITEE: gitee.com/yohole/yohole.git
